### ISSUE TITLE
It doesn't run

### ISSUE THREAD

**Issue by hamukazu** [kenkoooo/jupyter-autopep8#3]
Hello,
I am trying to run jupyter-autopep8. After installing it, I pushed the toolbar button selecting a cell but nothing happened. The symptom is the same when I type Ctrl+L.

The following is the working environment copied from the "about" message:
```
The version of the notebook server is 4.1.0-c8ab429 and is running on:
Python 3.5.1 (default, Jun 22 2016, 11:13:32) 
[GCC 4.8.4]
```

**Comment by kenkoooo** [comment]
It requires `autopep8` to be imported from the notebook server. Please check whether it is already installed.

**Comment by kenkoooo** [comment]
I'm sorry, I found a bug.
I'll fix it as soon as possible.

**Comment by kenkoooo** [comment]
It may be fixed. Please check.
